version: "3.8"
services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pace
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./server
    image: api
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ./server/src:/src
    command: node ./dist/index.js
    environment:
      PORT: 80
      NODE_ENV: development
      DB_USER: SA
      DB_HOST: db
      DB_NAME: pace
      DB_PASSWORD: password
      DB_PORT: 5432
      JWT_SECRET: PaceS3cret!
    depends_on:
      - db
volumes:
  db:
